# Algorithm parameters
ACTOR_LR = 0.0005
CRITIC_LR = 0.0005
GAMMA = 0.99
TAU = 0.001
BUFFER_SIZE = 1e6
MINIBATCH_SIZE = 1024
TARGET_ENTROPY_START = 0.3
TARGET_ENTROPY_STOP = 0.3
TARGET_ENTROPY_STET = 1e5
ALPHA_LR = 0.001
N_ENVS = 16
N_MAX_STEPS = 1e8

# Network parameters
ACTOR_LAYER1 = 138
CRITIC_LAYER1 = 384
ACTOR_LAYER2 = 66
CRITIC_LAYER2 = 162

ENCODING_INPUT = 2 * 66
ENCODING_LAYER1 = 40
ENCODING_OUTPUT = 10

# Environment arguments
NUM_AGENTS = 5
ACTOR_INPUT_LEN = 12
CRITIC_INPUT_LEN = 36
CRITIC_OUTPUT_LEN = 5
ACTOR_OUTPUT_LEN = 5

# Other parameters
SEED = int(1234)
ENV_SEED = int(1)
EXPERIMENT_NAME = 'FCMNet_binary'
USER_NAME = 'Yutong'
EVALUE_INTERVAL = 1e5
EVALUE_EPISODES = 16
SAVE_INTERVAL = 1e7

alg_args = {'actor_lr': ACTOR_LR, 'critic_lr': CRITIC_LR, 'GAMMA': GAMMA, 'TAU': TAU, 'BATCH_SIZE': BUFFER_SIZE,
            'MINIBATCH_SIZE': MINIBATCH_SIZE, 'TARGET_ENTROPY_START': TARGET_ENTROPY_START,
            'TARGET_ENTROPY_STOP': TARGET_ENTROPY_STOP,
            'TARGET_ENTROPY_STET': TARGET_ENTROPY_STET,
            'ALPHA_LR': ALPHA_LR, 'N_ENVS': N_ENVS, 'SEED': SEED, 'N_MAX_STEPS': N_MAX_STEPS,
            'ACTOR_LAYER1': ACTOR_LAYER1, 'CRITIC_LAYER1': CRITIC_LAYER1,
            'ACTOR_LAYER2': ACTOR_LAYER2,
            'CRITIC_LAYER2': CRITIC_LAYER2, 'ENCODING_INPUT': ENCODING_INPUT, 'ENCODING_LAYER1': ENCODING_LAYER1,
            'ENCODING_OUTPUT': ENCODING_OUTPUT,
            'NUM_AGENTS': NUM_AGENTS,
            'ACTOR_INPUT_LEN': ACTOR_INPUT_LEN, 'CRITIC_INPUT_LEN': CRITIC_INPUT_LEN,
            'CRITIC_OUTPUT_LEN': CRITIC_OUTPUT_LEN,
            'ACTOR_OUTPUT_LEN': ACTOR_OUTPUT_LEN}
